### ISSUE TITLE
Outdated repo?

### ISSUE THREAD

**Issue by dolmen** [llOzzeell/TechnicHubController#2]
Hi,

I've seen this repo mentionned on the Eurobricks forum:
https://www.eurobricks.com/forum/index.php?/forums/topic/173892-controlz-app-for-control-powered-up-v211/&page=6

But the last commit on this repo is 13 months old.

Is it still open source ? Did you just forgot to push the code here ?

**Comment by llOzzeell** [comment]
Hello, the Controlz project is no longer open source.
Unfortunately this repository will no longer be updated.
